### ISSUE TITLE
Check for updates button sqeezed when the error message is too long

### ISSUE THREAD

**Issue by SaltfishAmi** [birtles/rikaichamp#308]
![Untitled2](https://user-images.githubusercontent.com/14184974/85654718-36b5c380-b6e1-11ea-8d7a-4db727b45b9d.png)

Like this, the `Check for updates` button is normal for most of the time but when there's a long error message it will be sqeezed out.
For a quick (and dirty) fix, a simple `updateButton.setAttribute('style', 'min-width: 10em;');` or `updateButton.setAttribute('style', 'white-space: nowrap;');` just solved this perfectly on my browser.
This is reproduced with FF dev edition 78.0b9 with default dark theme, and Waterfox Current 2020.06 with Photon Dynamic 1.0 theme. Chrome is unfortunately beyond my knowledge.

**Comment by birtles** [comment]
I'm actually more concerned about the fact that the update failed. Does that happen often? Did it resolve later?

Or was this a result of running on always-on-private-browsing mode?

As for the issue itself, I guess we really should make the button wrap properly?

`chrome://browser/content/extension.css` has the following rule:

```css
button.browser-style,
select.browser-style {
  background-color: #fbfbfb;
  border: 1px solid #b1b1b1;
  box-shadow: 0 0 0 0 transparent;
  font: caption;
  height: 24px;
  outline: 0 !important;
  padding: 0 8px 0;
  transition-duration: 250ms;
  transition-property: box-shadow, border;
}
```

So presumably we could just override that to be `height: auto; min-height: 24px;` ?

Would adding a rule like the following to `options.css` work?

```css
#rikaichamp_options button.browser-style {
  /* Allow buttons to increase in height */
  height: auto;
  min-height: 24px;
}
```

**Comment by SaltfishAmi** [comment]
> 
> 
> I'm actually more concerned about the fact that the update failed. Does that happen often? Did it resolve later?
> 
> Or was this a result of running on always-on-private-browsing mode?
> 
> As for the issue itself, I guess we really should make the button wrap properly?
> 
> `chrome://browser/content/extension.css` has the following rule:
> 
> ```css
> button.browser-style,
> select.browser-style {
>   background-color: #fbfbfb;
>   border: 1px solid #b1b1b1;
>   box-shadow: 0 0 0 0 transparent;
>   font: caption;
>   height: 24px;
>   outline: 0 !important;
>   padding: 0 8px 0;
>   transition-duration: 250ms;
>   transition-property: box-shadow, border;
> }
> ```
> 
> So presumably we could just override that to be `height: auto; min-height: 24px;` ?
> 
> Would adding a rule like the following to `options.css` work?
> 
> ```css
> #rikaichamp_options button.browser-style {
>   /* Allow buttons to increase in height */
>   height: auto;
>   min-height: 24px;
> }
> ```

The failure itself is nothing. I just moved to new apartment and Internet was not ready. I'll try the css rules later.

**Comment by SaltfishAmi** [comment]
![Capture](https://user-images.githubusercontent.com/14184974/85827896-c2028800-b7b9-11ea-9cad-536414d53131.PNG)
![Capture2](https://user-images.githubusercontent.com/14184974/85827903-c3cc4b80-b7b9-11ea-9481-d0cf6123ee8e.PNG)

`height: auto; min-height: 24px;` works fine but not perfect in terms of appearance I'd say.
How about `text-align: center;` and a little `padding-bottom`?

**Comment by birtles** [comment]
Sorry for the delay.

On further thought, maybe your original suggestion is fine (I'm a bit concerned about adding `padding-bottom` since it will make the single-line case look different and we should probably match browser-styles for that). I want to avoid the `min-width: 10em` approach, however, since that label is localized and could potentially be quite long.

Maybe we could go with:

```css
#rikaichamp_options button.browser-style {
  /* Don't wrap buttons */
  white-space: nowrap;
  /* If they do wrap, however, make them look nice */
  height: auto;
  min-height: 24px;
  text-align: center;
}
```

That way if it does wrap, it shouldn't overflow the button border and should be centered.
